config/routes.rb
Protov1App::Application.routes.draw do
  resources :users do
      member do
      get :going_games, :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :games, only: [:show, :create, :destroy, :edit, :update] do
        member do
      get :going_games
    end
  end
  resources :gamers, only: [:create, :destroy]
  resources :display_game_map, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :games, dependent: :destroy
  has_many :gamers, foreign_key: "player_id", dependent: :destroy
  has_many :going_games, through: :gamers, source: :going_game
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  before_save { self.email = email.downcase }
  before_create :create_remember_token	
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def already_going?(this_game)
    gamers.find_by(going_game_id: this_game.id)
  end

  def going!(this_game)
    gamers.create!(going_game_id: this_game.id)
  end

  def not_going!(this_game)
    gamers.find_by(going_game_id: this_game.id).destroy
  end

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update,:following, :followers]
  before_action :correct_user,   only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @game = @user.games.build
    @my_games = @user.games.paginate(page: params[:page], per_page: 5)
    @going_games = @user.going_games.paginate(page: params[:page], per_page: 5)
    @following = @user.following.paginate(page: params[:page])
    @followers = @user.followers.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/users_helper.rb
module UsersHelper
# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.
                          build(followed_id: @user.id),
                          remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_show_follow.html.erb
<div class="row">
  <!--div class="col-md-8"-->
    <% if @following.any? %>
      <% @users = @following %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  <!--/div-->
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<header class="intro">
 <h1> Update your profile </h1>
 <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>
</header>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<header class="sign_up_image">
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
</header>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<header class="user_show_page_image">

  <div class="padding">
    <div class="full col-sm-9">
                      
      <!-- content -->                      
      <div class="row">
        
       <!-- main col left --> 
       <div class="col-sm-2">
          <div class="panel panel-default"> 
            <div class="panel-body">
               <h4>
                <%= gravatar_for @user %>
                <%= @user.name %>
              </h4>           
            </div>
          </div>

          <div class="panel panel-default"> 
            <div class="panel-heading"> 
              <h4> User Stats </h4>
            </div>
            <div class="panel-body">
              <section class="stats">
                <%= render 'shared/stats' %>
              </section>
              <%= render 'follow_form' if signed_in? %>
            </div>
          </div>
        </div>

        <div class="col-sm-7">   

          <div role="tabpanel">

            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
              <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">My Games</a></li>
              <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">My Followers Games</a></li>
              <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Followers</a></li>
              <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Following</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane active" id="home">
                <div class="panel panel-default"> 
                  <div class="panel-body">
                    <% if @user.games.any? %>
                      <% for @my_game in @my_games %>
                      <ol class="list-group">
                        <li class="list-group-item my_game" > 
                          <div id = "display_game_details"> 
                            <%= render "shared/display_game_details" %>
                          </div>
                          <h4>
                          <% if current_user?(@my_game.user) %>
                            <%= link_to 'Edit ', edit_game_path(@my_game), remote: true %>
                            <%= link_to "delete ", @my_game, method: :delete,
                                             data: { confirm: "You sure?" } %>
                          <% end %>
                          </h4>
                        </li>
                      </ol>
                      <% end %>
                      <%= will_paginate @my_games %>
                    <% end %>
                  </div>
                </div>
              </div>
              <div role="tabpanel" class="tab-pane" id="profile">
                <div class="panel panel-default"> 
                  <div class="panel-body">
                    <% if @user.going_games.any? %>
                      <% for @going_game in @going_games %>
                      <ol class="list-group">
                        <li class="list-group-item my_game" > 
                          <h4 class = "my_game_sport" ><%= @going_game.sport %> </h4>
                          <h4 class = "my_game_sport" >
                            <%= @going_game.address %> 
                            <% if current_user?(@going_game.user) %>
                              <%= link_to "delete", current_user.gamers.find_by(going_game_id: @going_game.id), method: :delete,
                                             data: { confirm: "You sure?" } %>
                            <% end %>
                          </h4>
                        </li>
                      </ol>
                      <% end %>
                      <%= will_paginate @going_games %>
                    <% end %>
                  </div>
                </div>
              </div>
              <div role="tabpanel" class="tab-pane" id="messages">
                <div class="panel panel-default"> 
                  <div class="panel-body">
                    <% if @user.going_games.any? %>
                      <% for @going_game in @going_games %>
                      <ol class="list-group">
                        <li class="list-group-item my_game" > 
                          <%= render 'show_follow' %>
                        </li>
                      </ol>
                      <% end %>
                      <%= will_paginate @going_games %>
                    <% end %>
                  </div>
                </div>
              </div>
              <div role="tabpanel" class="tab-pane" id="settings">...</div>
            </div>
          </div>
        </div>


        <div class="col-sm-3">

        </div> 

      </div>
     </div>
 </header>

 <div class="modal fade" id="edit_game_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Games:</b> <%= @user.games.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>