config/routes.rb
Protov1App::Application.routes.draw do
  resources :users do
      member do
      get :going_games, :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :games, only: [:show, :create, :destroy, :edit, :update] do
        member do
      get :going_games
    end
  end
  resources :gamers, only: [:create, :destroy]
  resources :display_game_map, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/views/shared/_display_game_details.html.erb
<h4 class = "my_game_sport" ><%= @my_game.sport %> </h4> 
<h4 class = "my_game_address"><%= @my_game.address %>  

app/views/shared/_display_game_map.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:display_game_map, url: display_game_map_index_path) do |f| %>

      <%= f.label :sport %>
      <%= f.select :sport, options_for_select(["All", "Badminton", "Baseball", "Basket ball", "Billard", "Chess", "Climbing", "Cricket", "Cycling", "Fitness", "Football", "Golfing", "Hangout", "Hiking", "Jogging", "Motorbike", "Squash", "Swimming", "Table tennis", "Tennis", "US football", "Volley ball", "Yoga"])%>

      <%= f.label :location %>
      <%= f.text_field :location, placeholder: "Bangalore India"%>

  	<%= f.submit "Search Sport", class: "btn btn-large btn-primary" %>
	<% end %>
 </div>
</div>

app/views/shared/_edit_game_form.html.erb
   <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Edit sports event</h4>
      </div>
      <div class="modal-body">
        <%= form_for(@edit_game, remote: true, html: { style: "display:inline;" }) do |f| %>
          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_field :address, placeholder: "Newyork usa"%>
          </div>

          <div class="form-group">
            <%= f.label :sport %>
            <%= f.select :sport, options_for_select(["Badminton", "Baseball", "Basket ball", "Billard", "Chess", "Climbing", "Cricket", "Cycling", "Fitness", "Football", "Golfing", "Hangout", "Hiking", "Jogging", "Motorbike", "Squash", "Swimming", "Table tennis", "Tennis", "US football", "Volley ball", "Yoga"])%>    
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description,  placeholder: "Add a small description..."%>
          </div>

          <div class="date form-group" id='datetimepicker1'>
            <%= f.label :game_time %>
            <%= f.datetime_select :game_time, :order => [:month, :day, :year], :minute_step => 15 %>
          </div>

          <div class="form-group">
           <%= f.submit "Update", class: "btn btn-large btn-primary" %>
          </div>

       <% end %>

        <script type="text/javascript">
          $(function () {
            $('#datetimepicker1').datetimepicker();
          });
        </script>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_game_form.html.erb

              <% modal ||= false %>
              <% remote = modal ? true : false %>
              <%= form_for(@new_game, remote: remote, html: {role: :form, 'data-model' => 'game', 'data-type' => 'json'}) do |f| %>
                <div class="form-group">
                  <%= f.label :address %>
                  <%= f.text_field :address, placeholder: "Newyork usa"%>
                </div>

                <div class="form-group">
                  <%= f.label :sport %>
                  <%= f.select :sport, options_for_select(["Badminton", "Baseball", "Basket ball", "Billard", "Chess", "Climbing", "Cricket", "Cycling", "Fitness", "Football", "Golfing", "Hangout", "Hiking", "Jogging", "Motorbike", "Squash", "Swimming", "Table tennis", "Tennis", "US football", "Volley ball", "Yoga"])%>    
                </div>

                <div class="form-group">
                  <%= f.label :description %>
                  <%= f.text_area :description,  placeholder: "Add a small description..."%>
                </div>

                <div class="date form-group" id='datetimepicker1'>
                  <%= f.label :game_time %>
                  <%= f.datetime_select :game_time, :order => [:month, :day, :year], :minute_step => 15 %>
                </div>

                <div class="form-group">
                 <%= f.submit "Create", class: "btn btn-large btn-primary" %>
                </div>

            <% end %>

            <script type="text/javascript">
                $(function () {
                  $('#datetimepicker1').datetimepicker();
                });
            </script>

app/views/shared/_google_map.html.erb
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
    <div style='width: 100%;'>
      <div id="map" style='width: 100%; height: 400px;'></div>
    </div>
   <script type="text/javascript">

    handler = Gmaps.build('Google');

    function displayOnMap(json){

       var parsed_json = JSON.parse(json);
       var marker_url  = marker_image(parsed_json.saved_game.sport);
       var marker      = handler.addMarker({

        lat: parsed_json.saved_game.latitude,
        lng: parsed_json.saved_game.longitude,

        picture: {
                url: marker_image(parsed_json.saved_game.sport),
                width: 32,
                height: 37
         },

        infowindow: parsed_json.game_show

      }); 

       handler.map.centerOn(marker);
    }

    var my_lat = <%= @center_on_location_lat  %>;
    var my_lng = <%= @center_on_location_lng  %>;

    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){

    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    //handler.fitMapToBounds();
    handler.getMap().setCenter({lat: my_lat, lng: my_lng});
    handler.getMap().setZoom(12);
    
    });

    function marker_image(sport){

    if (sport == "Football"){
      image = "/assets/soccer.png"
    }
    else if (sport == "Cricket"){
      image = "/assets/cricket.png"
    }
    else if (sport == "Basket ball"){
      image = "/assets/basketball.png"
    }
    else if (sport == "Volley ball"){
      image = "/assets/volleyball.png"
    }
    else if (sport == "Badminton"){
      image = "/assets/badminton.png"
    }
    else if (sport == "Baseball"){
      image = "/assets/baseball.png"
    }
    else if (sport == "Billard"){
      image = "/assets/billard.png"
    }
    else if (sport == "Chess"){
      image = "/assets/chess.png"
    }
    else if (sport == "Climbing"){
      image = "/assets/climbing.png"
    }
    else if (sport == "Cycling"){
      image = "/assets/cycling.png"
    }
    else if (sport == "Fitness"){
      image = "/assets/fitness.png"
    }
    else if (sport == "Golfing"){
      image = "/assets/golfing.png"
    }
    else if (sport == "Hangout"){
      image = "/assets/hangout.png"
    }
    else if (sport == "Hiking"){
      image = "/assets/hiking.png"
    }
    else if (sport == "Jogging"){
      image = "/assets/jogging.png"
    }
    else if (sport == "Motorbike"){
      image = "/assets/motorbike.png"
    }
    else if (sport == "Squash"){
      image = "/assets/squash.png"
    }
    else if (sport == "Swimming"){
      image = "/assets/swimming.png"    
    }
    else if (sport == "Table tennis"){
      image = "/assets/tabletennis.png" 
    }
    else if (sport == "Tennis"){
      image = "/assets/tennis.png"                           
    }
    else if (sport == "US football"){
      image = "/assets/usfootball.png" 
    }
    else if (sport == "Yoga"){
      image = "/assets/yoga.png" 
     }
        return image;
    }

    </script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>