config/routes.rb
Protov1App::Application.routes.draw do
  resources :users do
      member do
      get :going_games, :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :games, only: [:show, :create, :destroy, :edit, :update] do
        member do
      get :going_games
    end
  end
  resources :gamers, only: [:create, :destroy]
  resources :display_game_map, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/game.rb
class Game < ActiveRecord::Base
	validates :address, presence: true
	geocoded_by :address
	after_validation :geocode
	belongs_to :user
	validates :user_id, presence: true

	has_many :reverse_gamers, foreign_key: "going_game_id", class_name: "Gamer", dependent: :destroy
	has_many :players, through: :reverse_gamers, source: :player

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
  respond_to :json, :html

  def create
  	@game = current_user.games.build(game_params)
    respond_to do |format|
      if @game.save
        @created_game = @game
        @game_info_window = render_to_string(:partial => 'games/show', :layout => false, :format => :html, :locals => { :@game => @game })
        #raise @game_show.inspect
        format.html {redirect_to current_user, notice: 'Game created !'}
        format.json {
          render :json => {
          :saved_game => @created_game, 
          :game_show => @game_info_window
          }
        }
        format.js {render json: @created_game.to_json}
      else
        render 'static_pages/home'
      end
    end
  end

  def destroy
    @game.destroy
    flash[:success] = "Sport deleted"
    redirect_to current_user
  end

  def edit 
    @edit_game = current_user.games.find(params[:id])
  end

  def update 
    @edit_game = current_user.games.find(params[:id])
    @my_game   = @edit_game
      if @edit_game.update_attributes(game_params)
      else
        render 'user/show'
      end
  end

  def show
  end

  private

    def game_params
      params.require(:game).permit(:address, :longitude, :latitude, :description, :sport, :game_time)
    end

     def correct_user
      @game = current_user.games.find_by(id: params[:id])
      redirect_to root_url if @game.nil?
    end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_edit.html.erb
<%= render "shared/edit_game_form" %>

app/views/games/_game.html.erb
<li>
  <h4><strong>Sport: </strong><%= @my_game.sport %></h4>
  <h4><strong>Address: </strong><%= @my_game.address %>
  <strong>Game time: </strong><%= @my_game.game_time %></h4>
</li>

app/views/games/_going.html.erb
<%= form_for(current_user.gamers.
                          build(going_game_id: @game.id),remote: true) do |f| %>
  <div><%= hidden_field_tag :going_game_id, @game.id %></div>
  <%= f.submit "Going", class: "btn btn-primary" %>
<% end %>

app/views/games/_going_game_form.html.erb
<% unless current_user?(@user) %>
  <div id="going_game_form">
  <% if current_user.already_going?(@game) %>
    <%= render 'games/not_going' %>
  <% else %>
    <%= render 'games/going' %>
  <% end %>
  </div>
<% end %>

app/views/games/_not_going.html.erb
<%= form_for(current_user.gamers.find_by(going_game_id: @game.id),
             html: { method: :delete },remote: true) do |f| %>
  <%= f.submit "Not going", class: "btn" %>
<% end %>

app/views/games/_show.html.erb
<div class="show_sports_info">
  <aside class="span4">
    <section>
		<p>
  		  <strong>Sport:</strong> 
  		    <%= @game.sport %>
		</p>
		<p>
  		  <strong>Description:</strong> 
  		    <%= @game.description %>
		</p>
		<p>
  		  <strong>Game time:</strong> 
          <% if @game.game_time? %>
  		    <%= @game.game_time.to_formatted_s(:long)  %>
          <% end %>
		</p>
    <p>
        <strong>Posted by:</strong> 
          <%= link_to @game.user.name , user_path(@game.user) %>
    </p>
    <p>
      <div id="total_gamers">
        <%= render 'games/total_gamers' %>
      </div>
    </p>
    <p>
      <div id="show_game_form">
        <% if signed_in? %>
          <%= render 'games/going_game_form' %>
        <% else %>
          <%= link_to "Sign up to join game", signup_path, class: "btn btn-large btn-primary" %>
        <% end %>
      </div>  
    </p>   
    </section>
  </aside>
</div>

app/views/games/_show.js.erb
<%= j(render :template => 'games/_show.html.erb', :locals  => {:game => @game, :user => game.user.id }) %>"

app/views/games/_show.json.erb
<div class="show_sports_info">
  <aside class="span4">
    <section>
		<p>
  		  <strong>Sport:</strong> 
  		    <%= @game.sport %>
		</p>
		<p>
  		  <strong>Description:</strong> 
  		    <%= @game.description %>
		</p>
		<p>
  		  <strong>Game time:</strong> 
          <% if @game.game_time? %>
  		    <%= @game.game_time.to_formatted_s(:long)  %>
          <% end %>
		</p>
    <p>
        <strong>Posted by:</strong> 
          <%= link_to @game.user.name , user_path(@game.user) %>
    </p>
    <p>
      <div id="total_gamers">
        <%= render 'games/total_gamers' %>
      </div>
    </p>
    <p>
      <div id="show_game_form">
        <% if signed_in? %>
          <%= render 'games/going_game_form' %>
        <% else %>
          <%= link_to "Sign up to join game", signup_path, class: "btn btn-large btn-primary" %>
        <% end %>
      </div>  
    </p>   
    </section>
  </aside>
</div>

app/views/games/_total_gamers.html.erb
<p>
  <%= @game.players.count %> <strong>Going</strong> 
</p>

app/views/games/edit.js.erb
$("#edit_game_modal").html("<%= escape_javascript(render 'edit') %>")
$("#edit_game_modal").modal("show")

app/views/games/update.js.erb
$("#display_game_details").html("<%= escape_javascript(render('shared/display_game_details')) %>")
$("#edit_game_modal").modal("hide")